#!/usr/bin/env bash

case "$1" in

  'setup:install')
    echo ""
    echo "Installing"
    echo ""
    # https://brew.sh/
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew update
    brew doctor

    brew install git

    # manage java versions
    # eg jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home/
    brew install jenv

    brew install node

    brew install bash bash-completion git

    # eg brew install adoptopenjdk15
    brew install adoptopenjdk

    npm install -g avn avn-nvm avn-n

    ;;

  'setup:upgrade')
    echo ""
    echo "Upgrading"
    echo ""
    brew upgrade node
    brew upgrade npm

    ;;


  'compile')
    echo ""
    echo "Compiling"
    echo ""
    ./gradlew compileJava
    ;;

  'test')
    echo ""
    echo "Running tests"
    echo ""
    ./gradlew test
    ;;

  'build')
    echo ""
    echo "Building"
    echo ""
    ./gradlew build assemble
    ;;

  'clean')
    echo ""
    echo "Cleaning"
    echo ""
    ./gradlew clean
    ;;

  'gradle:upgrade')
    echo ""
    echo "Upgrading gradle."
    echo ""
    if [ -z "$2" ]; then
      echo "Version not specified!"
    else
      ./gradlew wrapper --gradle-version $2 --distribution-type=all
    fi
    echo ""
    ;;

  'report:all')
    echo ""
    echo "Generating all reports."
    echo ""

    ./gradlew allTests
    ./gradlew JacocoTestReport
    ./gradlew allPmd
    ./gradlew aggregatePmd

    echo ""
    ;;

  'report:coverage')
    echo ""
    echo "Generating Jacoco test coverage report."
    echo ""
    ./gradlew :subProject1:allTests
    ./gradlew :subProject1:JacocoTestReport
    echo ""
    ;;

  'report:coverage:open')
    echo ""
    echo "Opening Jacoco test coverage report."
    echo ""
    open ./subprojects/subProject1/build/reports/jacoco/test/html/index.html
    echo ""
    ;;

  'report:test:open')
    echo ""
    echo "Opening Junit test report."
    echo ""
    open ./subprojects/subProject1/build/reports/tests/test/index.html
    echo ""
    ;;

  # kordamp targets

  'guide:create')
    echo ""
    echo "Creating guide"
    echo ""
    ./gradlew :guide:createGuide
    ;;

  'guide:open')
    echo ""
    echo "Opening guide"
    echo ""
    open ./docs/guide/build/guide/index.html
    ;;


  *)
    echo -e ""
    echo "Usage:"
    echo ""
    echo "$(tput setaf 5)    $me$(tput sgr0) $(tput setaf 3)<command>$(tput sgr0)"
    echo ""
    echo "Commands:"
    echo ""

    echo "$(tput setaf 3)    build                                      $(tput sgr0)      Compile and assemble application"
    echo "$(tput setaf 3)    clean                                      $(tput sgr0)      Delete generated and temporary files"

esac
